export const MOVIES = [
  {
    id: 1,
    title: 'The Godfather',
    year: 1972,
    director: 'Francis Ford Coppola',
    genre: 'Crime, Drama',
    rating: 9.2,
  },
  {
    id: 2,
    title: 'The Shawshank Redemption',
    year: 1994,
    director: 'Frank Darabont',
    genre: 'Drama',
    rating: 9.3,
  },
  {
    id: 3,
    title: 'The Dark Knight',
    year: 2008,
    director: 'Christopher Nolan',
    genre: 'Action, Crime, Drama',
    rating: 9.0,
  },
  {
    id: 4,
    title: 'The Lion King',
    year: 1994,
    director: 'Roger Allers, Rob Minkoff',
    genre: 'Animation, Adventure, Drama',
    rating: 8.5,
  },
  {
    id: 5,
    title: 'Star Wars: Episode IV - A New Hope',
    year: 1977,
    director: 'George Lucas',
    genre: 'Action, Adventure, Fantasy',
    rating: 8.6,
  },
  {
    id: 6,
    title: 'The Big Lebowski',
    year: 1998,
    director: 'Joel Coen, Ethan Coen',
    genre: 'Comedy, Crime',
    rating: 7.8,
  },
  {
    id: 7,
    title: 'Jurassic Park III',
    year: 2001,
    director: 'Joe Johnston',
    genre: 'Action, Adventure, Sci-Fi',
    rating: 5.9,
  },
  {
    id: 8,
    title: 'Batman v Superman: Dawn of Justice',
    year: 2016,
    director: 'Zack Snyder',
    genre: 'Action, Adventure, Sci-Fi',
    rating: 6.4,
  },
  {
    id: 9,
    title: 'Twilight',
    year: 2008,
    director: 'Catherine Hardwicke',
    genre: 'Drama, Fantasy, Romance',
    rating: 5.2,
  },
  {
    id: 10,
    title: 'Catwoman',
    year: 2004,
    director: 'Pitof',
    genre: 'Action, Crime, Fantasy',
    rating: 3.3,
  },
];

export type Movie = typeof MOVIES[number];
