export const PRODUCTS = [
  {
    id: 1,
    name: 'Wireless Bluetooth Earbuds',
    brand: 'Sony',
    color: 'Black',
    madeIn: 'China',
    price: 49.99,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 2,
    name: 'Smart Home Security Camera',
    brand: 'Ring',
    color: 'White',
    madeIn: 'USA',
    price: 89.99,
    rating: 4.2,
    inStock: false,
  },
  {
    id: 3,
    name: 'Portable Power Bank Charger',
    brand: 'Anker',
    color: 'Red',
    madeIn: 'Japan',
    price: 29.99,
    rating: 4.7,
    inStock: true,
  },
  {
    id: 4,
    name: 'Multi-Function Kitchen Blender',
    brand: 'Vitamix',
    color: 'Silver',
    madeIn: 'Germany',
    price: 79.99,
    rating: 4.8,
    inStock: true,
  },
  {
    id: 5,
    name: 'Professional Hair Dryer',
    brand: 'Dyson',
    color: 'Purple',
    madeIn: 'Italy',
    price: 59.99,
    rating: 4.5,
    inStock: false,
  },
  {
    id: 6,
    name: 'Waterproof Fitness Tracker Watch',
    brand: 'Fitbit',
    color: 'Blue',
    madeIn: 'South Korea',
    price: 129.99,
    rating: 4.2,
    inStock: true,
  },
  {
    id: 7,
    name: 'Stainless Steel Water Bottle',
    brand: 'Hydro Flask',
    color: 'Green',
    madeIn: 'China',
    price: 19.99,
    rating: 4.6,
    inStock: true,
  },
  {
    id: 8,
    name: 'Cordless Drill/Driver Kit',
    brand: 'DeWalt',
    color: 'Yellow',
    madeIn: 'USA',
    price: 149.99,
    rating: 4.9,
    inStock: true,
  },
  {
    id: 9,
    name: 'Compact Air Fryer',
    brand: 'Ninja',
    color: 'Black',
    madeIn: 'Germany',
    price: 99.99,
    rating: 4.4,
    inStock: false,
  },
  {
    id: 10,
    name: 'High-Speed HDMI Cable',
    brand: 'AmazonBasics',
    color: 'Black',
    madeIn: 'China',
    price: 14.99,
    rating: 4.3,
    inStock: true,
  },
];

export type Product = typeof PRODUCTS[number];
